name: compass
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy>=1.20
  - gdal>=3.3
  - isce3>=0.14.0
  - pandas>=1.4
  - pyproj>=3.3
  - pysolid>=0.3
  - ruamel.yaml>=0.15
  - scipy>=1.0,
  - yamale>=4.0
  - h5py>=3.5
  - shapely>=1.8
  - requests>=2.0
