version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build COMPASS docker image"
          command: |
            docker build . -f docker/Dockerfile -t test_image
      - run:
          name: "Run tests"
          command: |
            docker run --entrypoint "cd ~/OPERA/COMPASS &&\
                                    conda init bash &&\
                                    conda activate COMPASS &&\
                                    python -m pytest"

workflows:
  build-workflow:
    jobs:
      - build
