version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build COMPASS docker image"
          command: |
            docker build . -f docker/Dockerfile -t test_image
      - run:
          name: "Run tests"
          command: |
            docker run --rm test_image -m pip install pytest && ls
            /home/compass_user/OPERA/COMPASS

workflows:
  build-workflow:
    jobs:
      - build
