version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Build COMPASS docker image"
          command: |
            bash docker/build_docker_cslc.sh

workflows:
  build-workflow:
    jobs:
      - build
